# Generated by Django 3.1.7 on 2021-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('mark', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('specialid', models.IntegerField(unique=True)),
            ],
        ),
    ]
