# Generated by Django 3.1.7 on 2021-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210316_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firsttable',
            old_name='head',
            new_name='name',
        ),
        migrations.AddField(
            model_name='firsttable',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
